Repository 6-CSE/AnyLangHack, pull requests merged in 2021-09, with the labels that each got.

#3 README - Details and Decorum
  README.md
Labels: hacktoberfest-accepted

#4 Added python helpful
  PythonImportant/Books.py
  PythonImportant/python_important.py
Labels: hacktoberfest-accepted

#2 send email script ready
  SendEmail/send_email.py
Labels: hacktoberfest-accepted

#7 readme added for mail script
  SendEmail/README.md
Labels: hacktoberfest-accepted

#5 BFS
  BFS/Node.py
  BFS/bfs.py
  BFS/heuristic.py
  BFS/hill.py
  BFS/main.py
  BFS/run.sh
  BFS/utils.py
Labels: hacktoberfest-accepted

#6 RSA Algorithm
  RSA/README.md
  RSA/rsa.py
Labels: hacktoberfest-accepted

#8 added searching algorithms
  searching_algorithms/BeamSearch.py
  searching_algorithms/Literal.py
  searching_algorithms/Node.py
  searching_algorithms/Readme.md
  searching_algorithms/TabuSearch.py
  searching_algorithms/VariableNeighbourhoodDescent.py
  searching_algorithms/main.py
  searching_algorithms/utils.py
Labels: enhancement, hacktoberfest-accepted

#10 Added GID script
  Google Image Downloader/googleImageDownloader.py
Labels: hacktoberfest-accepted

#14 Added README.md for GID
  Google Image Downloader/README.md
Labels: documentation

#16 Readme network scanner
  Network Scanner/README.md
  Network Scanner/networkScanner.py
Labels: documentation, hacktoberfest-accepted

#15 Added script for Network Scanner
  Network Scanner/networkScanner.py
Labels: enhancement

#12 added Tsp Algorithm
  TSP_algorithms/Ant.py
  TSP_algorithms/AntColony.py
  TSP_algorithms/Greedy.py
  TSP_algorithms/Readme.md
  TSP_algorithms/graph.png
  TSP_algorithms/main.py
  TSP_algorithms/run.sh
Labels: enhancement, hacktoberfest-accepted

#17 added readme and proper comments
  SubdomainFinder/README.md
  SubdomainFinder/crawler.py
Labels: hacktoberfest-accepted
